# jekyll configuration
# --------------------
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-redirect-from
highlighter: rouge
paginate: 1
markdown: kramdown
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile', 'run.sh', 'CNAME']

# site configuration
# ------------------
url: https://urbem.github.io
title: 西城
description: 'How should I greet, with silence and tears'
keywords: 'Life, Love, Music, Moive, Book, Reader'
author: Hang Yan
email: yanhangyhy@gmail.com

# google analytics
# ----------------

# github ribbon
# -------------
github_username: hangyan

# comments with disqus
# --------------------
disqus_username: yanhangyhy
