- service: github
  username: hangyan
  url: http://www.github.com/hangyan
- service: douban
  username: yayu
  url: http://book.douban.com/people/yanhangyhy/collect
- service: tec-blog
  username: yayu
  url: http://hyan.in/
